#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8085" \
    s6-setuidgid abc java -Dsuwayomi.suwayomi-server.config.server.rootDir="/config" -jar /app/suwayomi-server/Suwayomi-Server.jar \
    -nobrowser -data=/config
